### ISSUE TITLE
vite error: ReferenceError: module is not defined

### ISSUE THREAD

**Issue by btakita** [epoberezkin/fast-deep-equal#124] opened 2021-07-17 06:21 UTC
Looks like there needs to be a esm "module" export needed.

2:21:41 AM [vite] ✨ dependencies updated, reloading page...
2:21:41 AM [vite] new dependencies found: @ctx-core/array, @ctx-core/event-log, fast-deep-equal/es6, updating...
2:21:42 AM [vite] Error when evaluating SSR module /@fs/user/project/node_modules/.pnpm/fast-deep-equal@3.1.3/node_modules/fast-deep-equal/es6/index.js:
ReferenceError: module is not defined
    at /@fs/home/user/project/node_modules/.pnpm/fast-deep-equal@3.1.3/node_modules/fast-deep-equal/es6/index.js:9:1
    at instantiateModule (/home/user/project/node_modules/.pnpm/vite@2.4.2/node_modules/vite/dist/node/chunks/dep-11db14da.js:73323:166)

**Comment by epoberezkin** [comment] 2021-08-14 09:00
duplicate of #105

**Closed as completed by epoberezkin** 2021-08-14 09:00 UTC
